#!/usr/bin/env python3
"""Push apps-script/ to a Shorashim Apps Script project and point its web app deployment at it.

Usage:
  python3 apps-script/deploy.py --env staging ["description"]   # staging (npm run test:e2e does this)
  python3 apps-script/deploy.py ["description"]                 # production
  python3 apps-script/deploy.py --status                        # which commit each env is running
  python3 apps-script/deploy.py --set-console-password [--env staging]   # the /admin console password

Every deployed version is labelled with the commit it came from ("a1b2c3d description"), so
--status shows exactly what is live. Guards:
- the backend files (apps-script/, shared/) must be committed; staging accepts --allow-dirty, which
  labels the version "<sha>-dirty", so work in progress can be tried there;
- production also requires the staging suite (npm run test:e2e) to have passed on this exact
  commit. --force skips that, for emergencies only.

--content-only updates the project code without releasing it to the web app. Use it before
adding OAuth scopes: the owner authorizes them by running `setup` in the editor, and only then
is the new version released, so the live web app never runs with unauthorized scopes.

The booking rules come from shared/rules.js, the same module the website imports; the `export `
keyword is stripped on the way up so Apps Script sees plain globals.

IDs and secrets live in ~/.config/gcloud/shorashim/booking-config.json (production) and
booking-config.staging.json, never in this public repo. They are written into a generated
Config.js file that exists only inside the Apps Script project. The first run creates the project
and a web app deployment whose URL then stays fixed.
"""
import argparse
import json
import pathlib
import re
import subprocess
import sys

from google.auth.transport.requests import AuthorizedSession, Request
from google.oauth2.credentials import Credentials

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
SHARED = ROOT / "shared"
CRED_DIR = pathlib.Path.home() / ".config/gcloud/shorashim"
ENVS = {
    "production": {"config": CRED_DIR / "booking-config.json", "title": "Shorashim Booking"},
    "staging": {"config": CRED_DIR / "booking-config.staging.json", "title": "Shorashim Booking (staging)"},
}
BACKEND_PATHS = ("apps-script", "shared")
API = "https://script.googleapis.com/v1"
CONFIG_KEYS = (
    "calendars", "hmacSecret", "ownerEmail", "notifyEmail", "webAppUrl", "recaptchaSecret", "adminSheetId",
    "availabilitySheetId", "testHooks", "pricesUrl", "pricesSheetId", "consolePasswordHash", "recaptchaMinScore",
)


def git(*args):
    return subprocess.run(["git", *args], cwd=ROOT, check=True, capture_output=True, text=True).stdout.strip()


def e2e_passed(tree):
    """scripts/e2e.sh appends the tree hash of every commit the staging suite passed on."""
    marker = pathlib.Path(git("rev-parse", "--absolute-git-dir")) / "e2e-passed"
    return marker.exists() and tree in marker.read_text().split()


def session():
    creds = Credentials.from_authorized_user_file(str(CRED_DIR / "token.json"))
    creds.refresh(Request())
    return AuthorizedSession(creds)


def call(s, method, url, **kwargs):
    r = s.request(method, url, **kwargs)
    if not r.ok:
        sys.exit(f"{method} {url} -> {r.status_code}: {r.text[:800]}")
    return r.json()


def save(path, cfg):
    path.write_text(json.dumps(cfg, indent=2, ensure_ascii=False))
    path.chmod(0o600)


def apps_script_source(module_text):
    """Apps Script has no modules: every file shares one global scope. Dropping the `export `
    keyword turns shared/rules.js back into the plain globals the script expects, which is why it
    is written with `var` and function declarations and no export list."""
    return re.sub(r"^export ", "", module_text, flags=re.M)


def project_files(cfg):
    files = [{"name": "appsscript", "type": "JSON", "source": (HERE / "appsscript.json").read_text()}]
    files.append({"name": "rules", "type": "SERVER_JS", "source": apps_script_source((SHARED / "rules.js").read_text())})
    for path in sorted((HERE / "src").iterdir()):
        kind = {".js": "SERVER_JS", ".html": "HTML"}.get(path.suffix)
        if kind:
            files.append({"name": path.stem, "type": kind, "source": path.read_text()})
    config = {key: cfg.get(key, "") for key in CONFIG_KEYS}
    config["testHooks"] = cfg.get("testHooks") is True
    source = "// Generated by deploy.py. Do not edit.\nvar CONFIG = " + json.dumps(config, indent=2, ensure_ascii=False) + ";\n"
    files.append({"name": "Config", "type": "SERVER_JS", "source": source})
    return files


def push_version(s, cfg, description):
    script = f"{API}/projects/{cfg['scriptId']}"
    call(s, "PUT", f"{script}/content", json={"files": project_files(cfg)})
    return call(s, "POST", f"{script}/versions", json={"description": description[:250]})["versionNumber"]


def status():
    s = session()
    for env, spec in ENVS.items():
        cfg = json.loads(spec["config"].read_text())
        dep = call(s, "GET", f"{API}/projects/{cfg['scriptId']}/deployments/{cfg['deploymentId']}")
        version = dep["deploymentConfig"].get("versionNumber")
        desc = next(
            (v.get("description", "") for v in call(s, "GET", f"{API}/projects/{cfg['scriptId']}/versions").get("versions", [])
             if v.get("versionNumber") == version),
            "",
        )
        print(f"{env:<11} version {version}: {desc}")
    print(f"{'HEAD':<11} {git('rev-parse', '--short', 'HEAD')} {git('log', '-1', '--format=%s')}")


def set_console_password(env):
    """Stores the owner console's password (shorashimstay.com/admin) as "salt$hash" in the env's
    config file: HMAC-SHA256 over the password, keyed with a random salt plus the HMAC secret, the
    same computation as consoleLogin_ in Code.js. The password itself is never stored or printed.
    It takes effect on the next deploy of that environment. Read from CONSOLE_PASSWORD if set,
    otherwise asked for without echo."""
    import base64
    import getpass
    import hashlib
    import hmac
    import os
    import secrets

    path = ENVS[env]["config"]
    cfg = json.loads(path.read_text())
    password = os.environ.get("CONSOLE_PASSWORD") or getpass.getpass(f"Console password for {env}: ")
    if len(password) < 8:
        sys.exit("Use at least 8 characters.")
    salt = secrets.token_urlsafe(12)
    digest = hmac.new((salt + cfg["hmacSecret"]).encode(), password.encode(), hashlib.sha256).digest()
    cfg["consolePasswordHash"] = salt + "$" + base64.urlsafe_b64encode(digest).decode().rstrip("=")
    save(path, cfg)
    print(f"[{env}] Console password hash saved. Deploy {env} for it to take effect.")


def main():
    p = argparse.ArgumentParser(description="Deploy the booking backend to Apps Script.")
    p.add_argument("description", nargs="?", default="deploy")
    p.add_argument("--env", choices=ENVS, default="production")
    p.add_argument("--content-only", action="store_true", help="update the editor code without releasing it")
    p.add_argument("--allow-dirty", action="store_true", help="staging only: deploy uncommitted backend changes")
    p.add_argument("--force", action="store_true", help="production only: skip the staging-suite check")
    p.add_argument("--status", action="store_true", help="show which commit each environment runs")
    p.add_argument("--set-console-password", action="store_true", help="set the /admin console password (stored hashed)")
    args = p.parse_args()
    if args.status:
        return status()
    if args.set_console_password:
        return set_console_password(args.env)

    sha = git("rev-parse", "--short", "HEAD")
    dirty = bool(git("status", "--porcelain", "--", *BACKEND_PATHS))
    if dirty and not (args.allow_dirty and args.env == "staging"):
        sys.exit(
            "Uncommitted changes in apps-script/ or shared/. Commit them first"
            + (", or use --allow-dirty to try them on staging." if args.env == "staging" else ".")
        )
    if args.env == "production" and not args.force and not e2e_passed(git("rev-parse", "HEAD^{tree}")):
        sys.exit(f"The staging suite has not passed on {sha}. Run `npm run test:e2e` first (or --force in an emergency).")
    label = f"{sha}{'-dirty' if dirty else ''} {args.description}"

    spec = ENVS[args.env]
    cfg = json.loads(spec["config"].read_text())
    s = session()

    if not cfg.get("scriptId"):
        cfg["scriptId"] = call(s, "POST", f"{API}/projects", json={"title": spec["title"]})["scriptId"]
        save(spec["config"], cfg)

    if not cfg.get("deploymentId"):
        version = push_version(s, cfg, "initial")
        dep = call(
            s,
            "POST",
            f"{API}/projects/{cfg['scriptId']}/deployments",
            json={"versionNumber": version, "manifestFileName": "appsscript", "description": "web app"},
        )
        cfg["deploymentId"] = dep["deploymentId"]
        cfg["webAppUrl"] = next(
            (p["webApp"]["url"] for p in dep.get("entryPoints", []) if "webApp" in p),
            f"https://script.google.com/macros/s/{dep['deploymentId']}/exec",
        )
        save(spec["config"], cfg)

    if args.content_only:
        call(s, "PUT", f"{API}/projects/{cfg['scriptId']}/content", json={"files": project_files(cfg)})
        print(f"[{args.env}] Updated project code only (not released to the web app).")
        print(f"Editor:  https://script.google.com/d/{cfg['scriptId']}/edit")
        return

    version = push_version(s, cfg, label)
    call(
        s,
        "PUT",
        f"{API}/projects/{cfg['scriptId']}/deployments/{cfg['deploymentId']}",
        json={
            "deploymentConfig": {
                "scriptId": cfg["scriptId"],
                "versionNumber": version,
                "manifestFileName": "appsscript",
                "description": label[:250],
            }
        },
    )
    print(f"[{args.env}] Deployed version {version}: {label}")
    print(f"Web app: {cfg['webAppUrl']}")
    print(f"Editor:  https://script.google.com/d/{cfg['scriptId']}/edit")


if __name__ == "__main__":
    main()
